language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script: mvn clean deploy --settings travis_settings.xml

# travis encrypt -r nhl/bootique-jersey "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r nhl/bootique-jersey "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "CKj2vfyCfJUSYTbDHrBgwTLuPxU8v0qVj2Ye1D0tXCsQjGj7KPwm9FJvvFfofiAK/H2qnYFpVvwubmgZBpEErnwvZnDS2kz8ULRGQT2NVXA/spdbVVoi1patzBrLYbLUksPKlbAaPoePlPb1jHGg610RGpCDauy7FMBctbzbQqfgBAQVVFE08mVhxeS2/lSaCg5XdnlELHXVvl0VCedNh37NSg/zW9JhBHjmlsVvSHB6ajDakjMFoUP2HzEekBeP4W2S8QRBznY5Up85ZqgpqMEwQ6ElqJMoaIKQAy/AWFMiNAHY4IwQlehP4liqn/4SDtT/VL2aT/lFIgUpTNPlUVUeUpCnFu26JQ2doR6OyL8Ta3Zco1fLv1msPj0zAO37Q2fngqa+eja3nbjz2DhBlSxwY8mxSMm6CdRPDt49nDM7ZlywFDo+9DqG0J+whoFj4w3V4VpDvKDQKOesuCR8GPKXlci6Dpo7AsxqdeC7rShNLiewgWhlqgtDfwpQMJsSB4+wjEVHpU2GtKMLQkP+iEk5iAZQeDzQDTTk/VO0wxtnzeTNXHzrtjGvN1BhFPqS69U+v6YpebQBuAmt+Vwu4IJiE+LImjyquPSYZRnYgqA2ttTPXYpIE7LLtR/Xsgax5Qe4+aqOX1fKMlOU1yg2xjWf7Bi7XGeSqWhxoiyOvXY="
    - secure: "Noqln/c4z9sYUJlLbdD76XQmWJb/Ir0O0ndys0UzC4xgIUe+lG3/nVcP13SDS5IYl92ehyzzOXQoWsDMhw6IgyrUNkcBKm05DMFxvfvb4i8wgtflCuXIQJcrecbgqEnyOSwMFJB6aIKwuK/ox9UXBRJMWab7nKbLgm5sVM6wn1+6lIqaJIWEOcR5RiMtcvWMPsPZ3KOyJ3ltBhhqTDlL60EHfzyF8uZx7C0Rjm4BUvpK0TpBlODz7VMBrFBj6QVvKbfhixAEJB3PtZ3NzZoz1PpKN6DekpcX5aWLSP3CZxRUd/p1ajF/BidGpqfJbAITLj9X8Dl1635Fyf6RWXdoE2tfv/5WvSpZZ/D8oK6Zze9Or99VVUQcBOxEfNLw7F2bQ7iBfiWj7tJk2RycFDHscQ7bSh0geZjPVY+iGmO2eLOSBekIKbU4/VJvoHqtEtDptWLr5D2X3QH+2Lzb1B2jfa95GWPhGRm9J5pEW8qFY6G1V++REJHWMGvvbu8FSZET1jyAHhx8R+eLjGVx8cPtqUnFUbUkpJlccEYLGM63Xgw05kFr0UmsddMjSSBhG8TEZSGLnA7O/g/ikY08GAgWU6wlJg/Em9JKh29OTYc4meQYzE0BAbVDjvu3DXG3+/O0yFjeRB+BplUXakF52JGnvA9Un01T9ORgpkk8ADIxsEM="
